
INSERT INTO XXFE_RESP_APPROVER_LIST (APPLICATION_ID,RESPONSIBILITY_ID,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY) 
VALUES (101, 20434, '16', '17', NULL, SYSDATE, 1000, SYSDATE, 1000);


INSERT INTO XXFE_RESP_APPROVER_LIST (APPLICATION_ID,RESPONSIBILITY_ID,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY) 
VALUES (140, 20563, '18', '19', NULL, SYSDATE, 1000, SYSDATE, 1000);

INSERT INTO XXFE_RESP_APPROVER_LIST (APPLICATION_ID,RESPONSIBILITY_ID,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY) 
VALUES (160, 20456, '20', '21', NULL, SYSDATE, 1000, SYSDATE, 1000);

SELECT * FROM XXFE_RESP_APPROVER_LIST;

desc XXFE_RESP_APPROVER_LIST;
desc XXFE_USER_RESP_PROVISION;

select user_id from FND_USER where USER_NAME='SGUPTA';


select * from FND_RESPONSIBILITY_TL;

--========================================
--INSERTING INTO XXFE_USER_RESP_PROVISION
--=========================================

DESC XXFE_USER_RESP_PROVISION;

INSERT INTO XXFE_USER_RESP_PROVISION(USER_ID,RESPONSIBILITY_ID,STATUS,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY)
VALUES ('8591','20434','Not Assigned','16','17',NULL,SYSDATE,'1000',SYSDATE,'1000');

INSERT INTO XXFE_USER_RESP_PROVISION(USER_ID,RESPONSIBILITY_ID,STATUS,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY)
VALUES ('8591','20563','Not Assigned','18','19',NULL,SYSDATE,'1000',SYSDATE,'1000');

INSERT INTO XXFE_USER_RESP_PROVISION(USER_ID,RESPONSIBILITY_ID,STATUS,APPROVER1,APPROVER2,APPROVER3,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,UPDATED_BY)
VALUES ('8591','20456','Not Assigned','20','21',NULL,SYSDATE,'1000',SYSDATE,'1000');

SELECT * FROM XXFE_USER_RESP_PROVISION;





--====================================================
--SURESH UPDATED STATEMENT. STATEMENT IN VO WORKING!
--====================================================
SELECT DISTINCT TO_CHAR(FRT.RESPONSIBILITY_ID) ID, FRT.RESPONSIBILITY_NAME, A.APPLICATION_NAME,
'Default' Approver,
'Not Assigned' STATUS 
  FROM APPS.FND_RESPONSIBILITY_TL FRT
    ,APPS.FND_USER_RESP_GROUPS FUR
	,XXFE.XXFE_USER_RESP_PROVISION XRP
    ,XXFE.XXFE_RESP_APPROVER_LIST XRA
    ,FND_APPLICATION_TL A
  WHERE FRT.RESPONSIBILITY_ID 		= FUR.RESPONSIBILITY_ID
		AND FRT.APPLICATION_ID		= FUR.RESPONSIBILITY_APPLICATION_ID
		AND FRT.RESPONSIBILITY_ID	= XRP.RESPONSIBILITY_ID (+)
		AND FRT.RESPONSIBILITY_ID	= XRA.RESPONSIBILITY_ID (+)
		AND FRT.LANGUAGE(+)		= USERENV('LANG')
AND FRT.RESPONSIBILITY_NAME like nvl(:1,FRT.RESPONSIBILITY_NAME);


SELECT DISTINCT TO_CHAR(FRT.RESPONSIBILITY_ID) ID, FRT.RESPONSIBILITY_NAME, A.APPLICATION_NAME,
'Default' Approver,
'Not Assigned' STATUS 
  FROM APPS.FND_RESPONSIBILITY_TL FRT
    ,APPS.FND_USER_RESP_GROUPS FUR
	,XXFE.XXFE_USER_RESP_PROVISION XRP
    ,XXFE.XXFE_RESP_APPROVER_LIST XRA
    ,FND_APPLICATION_TL A WHERE
FRT.RESPONSIBILITY_ID 		= FUR.RESPONSIBILITY_ID AND FRT.APPLICATION_ID		= FUR.RESPONSIBILITY_APPLICATION_ID
AND FRT.RESPONSIBILITY_ID	= XRP.RESPONSIBILITY_ID (+)
AND FRT.RESPONSIBILITY_ID	= XRA.RESPONSIBILITY_ID (+)
AND A.application_id		= frt.application_id
AND FRT.LANGUAGE(+)		= USERENV('LANG')

select * from FND_RESPONSIBILITY_tl;

SELECT * FROM 
(;

SELECT DISTINCT TO_CHAR(FRT.RESPONSIBILITY_ID) ID, FRT.RESPONSIBILITY_NAME, A.APPLICATION_NAME, 'Default' Approver
, 'Not Assigned' STATUS FROM APPS.FND_RESPONSIBILITY_vL FRT ,APPS.FND_USER_RESP_GROUPS FUR ,XXFE.XXFE_USER_RESP_PROVISION XRP 
,XXFE.XXFE_RESP_APPROVER_LIST XRA ,FND_APPLICATION_TL A
WHERE (FRT.RESPONSIBILITY_ID = FUR.RESPONSIBILITY_ID AND FRT.APPLICATION_ID = FUR.RESPONSIBILITY_APPLICATION_ID AND FRT.RESPONSIBILITY_ID = XRP.RESPONSIBILITY_ID (+) AND FRT.RESPONSIBILITY_ID = XRA.RESPONSIBILITY_ID (+) AND A.application_id = frt.application_id AND FRT.RESPONSIBILITY_NAME like 'Appl%');



SELECT * FROM (
SELECT DISTINCT TO_CHAR(FRT.RESPONSIBILITY_ID) ID, FRT.RESPONSIBILITY_NAME, A.APPLICATION_NAME,
'Default' Approver,'Not Assigned' STATUS FROM APPS.FND_RESPONSIBILITY_TL FRT,APPS.FND_USER_RESP_GROUPS FUR
,XXFE.XXFE_USER_RESP_PROVISION XRP,XXFE.XXFE_RESP_APPROVER_LIST XRA,FND_APPLICATION_TL A
WHERE FRT.RESPONSIBILITY_ID 		= FUR.RESPONSIBILITY_ID AND FRT.APPLICATION_ID		= FUR.RESPONSIBILITY_APPLICATION_ID
AND FRT.RESPONSIBILITY_ID	= XRP.RESPONSIBILITY_ID (+)
AND FRT.RESPONSIBILITY_ID	= XRA.RESPONSIBILITY_ID (+)
AND A.application_id		= frt.application_id
AND FRT.LANGUAGE(+)		= USERENV('LANG')
) QRSLT  WHERE (RESPONSIBILITY_NAME like 'Appl%');

--=====================================================
--UPDATING APPROVER LIST WITH MODULE AND PROCESS OWNERS
--=====================================================
--FOR ALL APPLICATIONS EXCEPT 'GENERAL LEDGER'
	UPDATE XXFE_RESP_APPROVER_LIST
	SET MODULE_OWNER1 = APPROVER1 WHERE APPLICATION_ID != 101;
-- PROCESS OWNER: ROBIN RUTHERFORD(OM,Service Contracts,Install Base)
	UPDATE XXFE_RESP_APPROVER_LIST
	SET PROCESS_OWNER1 = 2310 WHERE application_id = 515;--CHECK APPLICATION ID
--PROCESS OWNER: GREG MAYER
		select * from fnd_user where user_name LIKE 'GMAY%';
		UPDATE XXFE_RESP_APPROVER_LIST
		SET PROCESS_OWNER1 = 2411 WHERE application_id = 222;
		-- NO RECORDS FOR RevPro IN FND_APPLICATION_TL
--PROCESS OWNER: JAMES MEDINA(GENERAL LEDGER,Payables)
select * from fnd_user where user_name LIKE 'JMED%';
select * from fnd_application_tl where application_name LIKE 'Pay%';
UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 2977 WHERE application_id = 200;

--PROCESS OWNER:Phuong Nguyen(Assets)
	select * from fnd_application_tl where application_name LIKE 'Ass%';
	select * from fnd_user where user_name LIKE 'PNGUYEN%';

	UPDATE XXFE_RESP_APPROVER_LIST
	SET PROCESS_OWNER1 = 1401 WHERE application_id = 140;
--PROCESS OWNER: Travis Loeffler(Inventory,Bills of Material,Work in Process,Engineering)
	select * from fnd_user where user_name LIKE 'TLO%';
	select * from fnd_application_tl where application_name LIKE 'Inven%';
	UPDATE XXFE_RESP_APPROVER_LIST
		SET PROCESS_OWNER1 = 1201 WHERE application_id = 401;
	UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 1201 WHERE application_id = 702;
  UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 1201 WHERE application_id = 706;
  UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 1201 WHERE application_id = 703;
--PROCESS OWNER: Vince Hemsley(Cost Management)
	select * from fnd_user where user_name LIKE 'VH%';
	select * from fnd_application_tl where application_name LIKE 'Cost%';
	UPDATE XXFE_RESP_APPROVER_LIST
	SET PROCESS_OWNER1 = 1209 WHERE application_id = 707;
--PROCESS OWNER: Terry O Malley(Purchasing,Oracle iProcurement)
select * from fnd_user where user_name LIKE 'TOMA%';
select * from fnd_application_tl where application_name LIKE 'Pur%';
UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 2010 WHERE application_id = 201;
  UPDATE XXFE_RESP_APPROVER_LIST
  SET PROCESS_OWNER1 = 2010 WHERE application_id = 178;
