CREATE OR REPLACE PACKAGE XX_VALIDATION AS
	PROCEDURE XX_REQUEST (USER_ID IN NUMBER,RESPONSIBILITY_ID IN NUMBER ,NOTIFICATION_ID IN NUMBER );
	PROCEDURE XX_REVOKE( USER_ID IN NUMBER,RESPONSIBILITY_ID IN NUMBER ,NOTIFICATION_ID IN NUMBER );
END XX_VALIDATION;


