set termout on
--set define on

--prompt 'Connecting to APPS schema..Please Enter Password'
--CONNECT APPS/&&passwd1

prompt 'Dropping table XXFE.XXFE_APPROVER_MIGRATE'
drop table "XXFE"."XXFE_APPROVER_MIGRATE"
/
prompt 'Creating table XXFE.XXFE_APPROVER_MIGRATE'
CREATE TABLE XXFE.XXFE_APPROVER_MIGRATE
(APPLICATION_ID NUMBER,RESPONSIBILITY_ID NUMBER, MODULE_OWNER1 VARCHAR2(100),MODULE_OWNER2 VARCHAR2(100),MODULE_OWNER3 VARCHAR2(100),MODULE_OWNER4 VARCHAR2(100),PROCESS_OWNER1 VARCHAR2(100),PROCESS_OWNER2 VARCHAR2(100),PROCESS_OWNER3 VARCHAR2(100),PROCESS_OWNER4 VARCHAR2(100));

PROMPT 'Recreating Synonym XXFE_APPROVER_MIGRATE'
DROP PUBLIC SYNONYM XXFE_APPROVER_MIGRATE
/

CREATE PUBLIC SYNONYM XXFE_APPROVER_MIGRATE
FOR XXFE.XXFE_APPROVER_MIGRATE
/

--undefine passwd1

--*********************************************
--CODE TO IMPORT DATA INTO THE TABLE 
--*********************************************
INSERT INTO xxfe_approver_migrate(APPLICATION_ID,RESPONSIBILITY_ID)
(SELECT APPLICATION_ID,RESPONSIBILITY_ID FROM xxfe_resp_approver_list);

DECLARE
L_APPID NUMBER;
L_RESID NUMBER;
L_MO1 NUMBER;
L_MO2 NUMBER;
L_MO3 NUMBER;
L_MO4 NUMBER;
L_PO1 NUMBER;
L_PO2 NUMBER;
L_PO3 NUMBER;
L_PO4 NUMBER;
L_MONAME1 VARCHAR2(100);
L_MONAME2 VARCHAR2(100);
L_MONAME3 VARCHAR2(100);
L_MONAME4 VARCHAR2(100);
L_PONAME1 VARCHAR2(100);
L_PONAME2 VARCHAR2(100);
L_PONAME3 VARCHAR2(100);
L_PONAME4 VARCHAR2(100);
CURSOR L_APPROVER IS SELECT APPLICATION_ID,RESPONSIBILITY_ID,MODULE_OWNER1,MODULE_OWNER2,MODULE_OWNER3,MODULE_OWNER4,PROCESS_OWNER1,PROCESS_OWNER2,PROCESS_OWNER3,PROCESS_OWNER4 FROM XXFE_RESP_APPROVER_LIST;
BEGIN
	OPEN L_APPROVER;
	LOOP
		FETCH L_APPROVER INTO L_APPID,L_RESID,L_MO1,L_MO2,L_MO3,L_MO4,L_PO1,L_PO2,L_PO3,L_PO4;
		SELECT max(user_name) INTO L_MONAME1 FROM fnd_user where USER_ID = L_MO1;
		SELECT max(user_name) INTO L_MONAME2 FROM fnd_user where USER_ID = L_MO2;
		SELECT max(user_name) INTO L_MONAME3 FROM fnd_user where USER_ID = L_MO3;
		SELECT max(user_name) INTO L_MONAME4 FROM fnd_user where USER_ID = L_MO4;
		SELECT max(user_name) INTO L_PONAME1 FROM fnd_user where USER_ID = L_PO1;
		SELECT max(user_name) INTO L_PONAME2 FROM fnd_user where USER_ID = L_PO2;
		SELECT max(user_name) INTO L_PONAME3 FROM fnd_user where USER_ID = L_PO3;
		SELECT max(user_name) INTO L_PONAME4 FROM fnd_user where USER_ID = L_PO4;
		INSERT INTO XXFE_APPROVER_MIGRATE VALUES(L_APPID,L_RESID,L_MONAME1,L_MONAME2,L_MONAME3,L_MONAME4,L_PONAME1,L_PONAME2,L_PONAME3,L_PONAME4); 
		EXIT WHEN L_APPROVER%NOTFOUND;
	END LOOP;
	CLOSE L_APPROVER;
END;
--*********************************************
--END OF CODE TO IMPORT DATA INTO THE TABLE 
--*********************************************

--*************************************************
--CODE TO IMPORT DATA INTO THE APPROVERS LIST TABLE 
--*************************************************
--USE 'APPROVER_MIGRATE.sql' file stored in BACKUPS/July15 For insert commands.
DECLARE
L_APPID NUMBER;
L_RESID NUMBER;
L_MO1 NUMBER;
L_MO2 NUMBER;
L_MO3 NUMBER;
L_MO4 NUMBER;
L_PO1 NUMBER;
L_PO2 NUMBER;
L_PO3 NUMBER;
L_PO4 NUMBER;
L_MONAME1 VARCHAR2(100);
L_MONAME2 VARCHAR2(100);
L_MONAME3 VARCHAR2(100);
L_MONAME4 VARCHAR2(100);
L_PONAME1 VARCHAR2(100);
L_PONAME2 VARCHAR2(100);
L_PONAME3 VARCHAR2(100);
L_PONAME4 VARCHAR2(100);
CURSOR L_APPROVER IS SELECT APPLICATION_ID,RESPONSIBILITY_ID,MODULE_OWNER1,MODULE_OWNER2,MODULE_OWNER3,MODULE_OWNER4,PROCESS_OWNER1,PROCESS_OWNER2,PROCESS_OWNER3,PROCESS_OWNER4 FROM XXFE_APPROVER_MIGRATE;
BEGIN
	OPEN L_APPROVER;
	LOOP
		FETCH L_APPROVER INTO L_APPID,L_RESID,L_MONAME1,L_MONAME2,L_MONAME3,L_MONAME4,L_PONAME1,L_PONAME2,L_PONAME3,L_PONAME4;
		SELECT max(user_id) INTO L_MO1 FROM fnd_user where USER_NAME = L_MONAME1;
		SELECT max(user_id) INTO L_MO2 FROM fnd_user where USER_NAME = L_MONAME2;
		SELECT max(user_id) INTO L_MO3 FROM fnd_user where USER_NAME = L_MONAME3;
		SELECT max(user_id) INTO L_MO4 FROM fnd_user where USER_NAME = L_MONAME4;
		SELECT max(user_id) INTO L_PO1 FROM fnd_user where USER_NAME = L_PONAME1;
		SELECT max(user_id) INTO L_PO2 FROM fnd_user where USER_NAME = L_PONAME2;
		SELECT max(user_id) INTO L_PO3 FROM fnd_user where USER_NAME = L_PONAME3;
		SELECT max(user_id) INTO L_PO4 FROM fnd_user where USER_NAME = L_PONAME4;
		INSERT INTO XXFE_RESP_APPROVER_LIST(APPLICATION_ID,RESPONSIBILITY_ID,MODULE_OWNER1,MODULE_OWNER2,MODULE_OWNER3,MODULE_OWNER4,PROCESS_OWNER1,PROCESS_OWNER2,PROCESS_OWNER3,PROCESS_OWNER4) VALUES(L_APPID,L_RESID,L_MO1,L_MO2,L_MO3,L_MO4,L_PO1,L_PO2,L_PO3,L_PO4); 
		EXIT WHEN L_APPROVER%NOTFOUND;
	END LOOP;
	CLOSE L_APPROVER;
END;