CREATE OR REPLACE FORCE VIEW "APPS"."XXFE_USER_RESP_PROVISION_V" ("RESPONSIBILITY_ID","RESPONSIBILITY_NAME","APPROVERS","STATUS")
AS
  SELECT TO_CHAR(FRT.RESPONSIBILITY_ID), FRT.RESPONSIBILITY_NAME, XXFE_APPROVERS_LIST. XXFE_GET_APPROVER_NAME(FRT.RESPONSIBILITY_ID),XRP.STATUS 
  FROM APPS.FND_RESPONSIBILITY_TL FRT
    ,APPS.FND_USER_RESP_GROUPS FUR
	,XXFE.XXFE_USER_RESP_PROVISION XRP
    ,XXFE.XXFE_RESP_APPROVER_LIST XRA
  WHERE FRT.RESPONSIBILITY_ID 		= FUR.RESPONSIBILITY_ID
		AND FRT.APPLICATION_ID		= FUR.RESPONSIBILITY_APPLICATION_ID
		AND FRT.RESPONSIBILITY_ID	= XRP.RESPONSIBILITY_ID (+)
		AND FRT.RESPONSIBILITY_ID	= XRA.RESPONSIBILITY_ID (+)
		AND FRT.LANGUAGE(+)			= USERENV('LANG')
/
